# Replace with your Discord Application ID
application_id: "1445996188129034269"

# Activity type: 0 = Playing, 1 = Streaming, 2 = Listening, 3 = Watching
type: 3

# Activity Details
name: "NABI"
details: "ANTIREVSHIT"
state: "Peace Over War"

# Activity Images
largeImageKey: "9543c657a9df0501dcba25df5bba8b37"
largeImageText: "nabi"
smallImageKey: "8844e503932c8890ead1adb98e131c2e"
smallImageText: "nabi"

# Activity URL (optional, works only with certain types)
url: "https://www.youtube.com/@womyxyz"

# Activity Buttons (optional)
buttons:
  - name: "JOIN"
    url: "https://discord.gg/revgng"
  - name: "CLICK"
    url: "https://revshit.xyz/"

# Activity Custom status
custom_status: "Watching Antirevshit"
custom_emoji: "ðŸ”¥"
