# Replace with your Discord Application ID
application_id: "1445996188129034269"

# Activity type: 0 = Playing, 1 = Streaming, 2 = Listening, 3 = Watching
type: 3

# Activity Details
name: "NABI"
details: "ANTIREVSHIT"
state: "Peace Over War"

# Activity Images
largeImageKey: "https://i.pinimg.com/originals/61/5e/69/615e6931fba185e1832d26cd0145d7dc.gif"
largeImageText: "na"
smallImageKey: "https://media.tenor.com/NZelT2JSDMcAAAAi/check.gif"
smallImageText: "bi"

# Activity URL (optional, works only with certain types)
url: "https://www.youtube.com/@womyxyz"

# Activity Buttons (optional)
buttons:
  - name: "JOIN"
    url: "https://discord.gg/revgng"
  - name: "CLICK"
    url: "https://revshit.xyz/"

# Activity Custom status
custom_status: "Watching Antirevshit"
custom_emoji: "ðŸ”¥"
