# Replace with your Discord Application ID
application_id: "1445996188129034269"

# Activity type: 0 = Playing, 1 = Streaming, 2 = Listening, 3 = Watching
type: 3

# Activity Details
discordPresence.name: "4REV"
discordPresence.details: "ANTIREVSHIT"
discordPresence.state: "Peace Over War"

# Activity Images
discordPresence.largeImageKey: "81b6caa33a40f38fa823041dfabbe6f0"
discordPresence.largeImageText: "nabi"
discordPresence.smallImageKey: "8844e503932c8890ead1adb98e131c2e"
discordPresence.smallImageText: "nabi"

# Activity URL (optional, works only with certain types)
url: "https://www.youtube.com/@womyxyz"

# Activity Buttons (optional)
buttons:
  - name: "JOIN"
    url: "https://discord.gg/4rev"
  - name: "CLICK"
    url: "https://antirevshit.world/"

# Activity Custom status
custom_status: "Watching Antirevshit"
custom_emoji: "ðŸ”¥"
